apiVersion: v1
kind: Secret
metadata:
  name: fortipipe-secrets
  namespace: dev
stringData:
  secret-key: "REPLACE_ME_WITH_A_SECURE_VALUE"
# NOTE: Replace the value above with a secure secret in your environment. 