image:
  repository: "REPLACE_WITH_REGISTRY/fortipipe"
  tag: "latest"
  pullPolicy: IfNotPresent

secretKey: "REPLACE_ME_WITH_A_SECURE_VALUE"

service:
  type: ClusterIP
  port: 8000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
